# p1
pipeline {
    agent any

    stages {
        stage('Preparation') { // for display purposes
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/amoravek/wso2-examples.git'
            }
        }
        stage('Build') {
            steps {
                sh 'newman run cicd-example/postman/WSO2_API_PUBLISHER.postman_collection.json -e cicd-example/rest-apis/petstore/Development.postman_environment.json --global-var username=admin --global-var password=admin --bail'
            }
        }
    }
}